#!/usr/bin/env python3
"""Add financial-services FDE data sources from the provided assessment workbook."""

from __future__ import annotations

import sqlite3
from datetime import date

from index_store import DB_PATH


TODAY = date.today().isoformat()
SOURCE_BATCH = "financial-fde-assessment"


FIELDS = [
    "resource_id",
    "platform_en",
    "platform_zh",
    "product_or_resource",
    "domain_en",
    "domain_zh",
    "country_region",
    "resource_formats",
    "source_format",
    "official_cli",
    "official_skill",
    "official_mcp",
    "official_sdk_api",
    "source_url",
    "official_status_en",
    "official_status_zh",
    "verification_status",
    "openness_level",
    "risk_level",
    "description_en",
    "description_zh",
    "source_dataset",
    "checked_at",
    "sort_order",
]


ROWS = [
    {
        "resource_id": "aar-0222",
        "platform_en": "SSE Info / SZSE Information",
        "platform_zh": "上证所信息网络 / 深证信息",
        "product_or_resource": "Exchange-authorized China A-share market data",
        "domain_en": "Financial exchange market data",
        "domain_zh": "金融交易所授权行情",
        "country_region": "China",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; build licensed MCP gateway",
        "official_sdk_api": "Exchange-authorized Level-1, Level-2, tick, order book, index, announcement, and statistics data",
        "source_url": "https://www.sseinfo.com/services/assortment/level1/",
        "official_status_en": "Official exchange information source",
        "official_status_zh": "官方交易所信息源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Licensed contract; display, non-display, redistribution, and derived-data rights must be confirmed separately",
        "risk_level": "Critical",
        "description_en": "Production-required China A-share, ETF, bond, fund, index, announcement, Level-1/Level-2, tick, and order-book market data source. Commercial use requires exchange/data-company licensing.",
        "description_zh": "国内 A 股、ETF、债券、基金、指数、公告、Level-1/Level-2、逐笔和盘口行情的生产级主源；商业使用必须完成交易所/信息公司授权。",
        "sort_order": 222,
    },
    {
        "resource_id": "aar-0223",
        "platform_en": "China Futures CTP / Exchange-authorized futures market data",
        "platform_zh": "期货公司 CTP / 交易所授权期货行情",
        "product_or_resource": "CTP and exchange-authorized futures trading and market data",
        "domain_en": "Financial exchange market data",
        "domain_zh": "金融交易所授权行情",
        "country_region": "China",
        "resource_formats": "SDK/API;CLI",
        "source_format": "official_web",
        "official_cli": "Broker/CTP trading gateway access",
        "official_skill": "",
        "official_mcp": "No official MCP; build read-only market-data tools separately from trading tools",
        "official_sdk_api": "Futures broker CTP, account, order, position, risk, and exchange-authorized futures market data",
        "source_url": "https://www.shfe.com.cn/",
        "official_status_en": "Official/broker-authorized source",
        "official_status_zh": "官方/期货公司授权源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Broker, CTP, leased line, and exchange data authorization required",
        "risk_level": "Critical",
        "description_en": "Production-required China commodity futures, financial futures, and options market-data/trading channel. Trading actions require strong permission separation, risk checks, audit logs, and human confirmation by default.",
        "description_zh": "国内商品期货、金融期货和期权的生产级行情/交易通道；交易动作必须与只读分析隔离，并默认要求风控、审计和人工确认。",
        "sort_order": 223,
    },
    {
        "resource_id": "aar-0224",
        "platform_en": "HKEX Real-time Data Services",
        "platform_zh": "HKEX Real-time Data Services",
        "product_or_resource": "HKEX real-time securities and derivatives data",
        "domain_en": "Financial exchange market data",
        "domain_zh": "金融交易所授权行情",
        "country_region": "Hong Kong",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; build licensed MCP gateway",
        "official_sdk_api": "HKEX real-time data services or authorized vendor feeds",
        "source_url": "https://www.hkex.com.hk/Services/Market-Data-Services/Real-Time-Data-Services/Overview?sc_lang=en",
        "official_status_en": "Official exchange source",
        "official_status_zh": "官方交易所来源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Licensed wholesale/vendor data; display, non-display, and redistribution rights required",
        "risk_level": "Critical",
        "description_en": "Primary source for Hong Kong securities, ETF, REIT, warrant, callable bull/bear contract, derivatives, issuer announcement, and information-stream use cases.",
        "description_zh": "港股、ETF、REITs、权证、牛熊证、衍生品、发行人公告和资讯流场景的主要授权行情源。",
        "sort_order": 224,
    },
    {
        "resource_id": "aar-0225",
        "platform_en": "Bloomberg Enterprise / B-PIPE",
        "platform_zh": "Bloomberg Enterprise / B-PIPE",
        "product_or_resource": "Bloomberg enterprise market data and B-PIPE",
        "domain_en": "Financial data and terminals",
        "domain_zh": "金融数据与终端",
        "country_region": "Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap enterprise data interfaces under contract",
        "official_sdk_api": "Bloomberg enterprise data products, B-PIPE, and Data License",
        "source_url": "https://www.bloomberg.com/professional/products/data/",
        "official_status_en": "Official enterprise source",
        "official_status_zh": "官方企业数据源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Contract pricing; exchange fees, terminal/server/API rights, and redistribution restrictions apply",
        "risk_level": "Critical",
        "description_en": "Global institutional real-time market data, news, reference data, and enterprise feed source. Strong production fit but high licensing and implementation complexity.",
        "description_zh": "全球机构级实时行情、新闻、参考数据和企业数据流来源；生产能力强，但商务授权和实施复杂度高。",
        "sort_order": 225,
    },
    {
        "resource_id": "aar-0226",
        "platform_en": "CME Group Market Data",
        "platform_zh": "CME Group Market Data",
        "product_or_resource": "CME market data platform and licensed futures/options data",
        "domain_en": "Financial exchange market data",
        "domain_zh": "金融交易所授权行情",
        "country_region": "US/Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap licensed data APIs or vendor feeds",
        "official_sdk_api": "CME Market Data Platform, authorized vendor feeds, DataMine, WebSocket/API options",
        "source_url": "https://www.cmegroup.com/market-data.html",
        "official_status_en": "Official exchange source",
        "official_status_zh": "官方交易所来源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Exchange data license; commercial, display, non-display, and redistribution rights required",
        "risk_level": "Critical",
        "description_en": "Production-priority source for global futures and options, market depth, options analytics, and historical DataMine data.",
        "description_zh": "全球期货/期权、Market Depth、期权分析和历史 DataMine 数据的生产优先来源。",
        "sort_order": 226,
    },
    {
        "resource_id": "aar-0227",
        "platform_en": "Moody's",
        "platform_zh": "Moody's",
        "product_or_resource": "Moody's API Hub and credit risk data",
        "domain_en": "Financial credit and risk data",
        "domain_zh": "金融信用与风险数据",
        "country_region": "Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap API Hub under enterprise terms",
        "official_sdk_api": "Moody's API Hub and API access request",
        "source_url": "https://developer.moodys.com/",
        "official_status_en": "Official developer source",
        "official_status_zh": "官方开发者来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Contract pricing; credit ratings, research, AI use, and redistribution restrictions are strict",
        "risk_level": "High",
        "description_en": "Credit ratings, default risk, credit research, bond/company/sovereign/financial-institution risk data, and API Hub access for credit-risk agents.",
        "description_zh": "面向信用风险 Agent 的评级、违约风险、信用研究、债券/主体/主权/金融机构风险数据和 API Hub 接入。",
        "sort_order": 227,
    },
    {
        "resource_id": "aar-0228",
        "platform_en": "MT Newswires",
        "platform_zh": "MT Newswires",
        "product_or_resource": "MT Newswires financial news feed",
        "domain_en": "Financial news and events",
        "domain_zh": "金融新闻与事件",
        "country_region": "Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap news search/subscription tools under license",
        "official_sdk_api": "News feed and enterprise delivery",
        "source_url": "https://www.mtnewswires.com/",
        "official_status_en": "Official source",
        "official_status_zh": "官方来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Contract pricing; news copyright, summaries, redistribution, and AI use require permission",
        "risk_level": "High",
        "description_en": "Real-time and near-real-time financial news feed for event-driven monitoring, market-moving news, company events, and market explanation agents.",
        "description_zh": "用于事件驱动监控、市场快讯、公司事件和市场异动解释 Agent 的实时/准实时金融新闻 Feed。",
        "sort_order": 228,
    },
    {
        "resource_id": "aar-0229",
        "platform_en": "Aiera",
        "platform_zh": "Aiera",
        "product_or_resource": "Aiera events, transcripts, and API",
        "domain_en": "Financial news and events",
        "domain_zh": "金融新闻与事件",
        "country_region": "Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap event calendar, transcript, audio, and Q&A access under license",
        "official_sdk_api": "API key and customer account event-data interface",
        "source_url": "https://www.aiera.com/",
        "official_status_en": "Official source",
        "official_status_zh": "官方来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Contract pricing; transcript, summary, redistribution, and client-output rights required",
        "risk_level": "High",
        "description_en": "Earnings calls, investor events, calendars, audio, real-time transcription, Q&A, and event research source for financial research agents.",
        "description_zh": "面向投研 Agent 的财报电话会、投资者活动、事件日历、音频、实时转录、问答和事件研究数据源。",
        "sort_order": 229,
    },
    {
        "resource_id": "aar-0230",
        "platform_en": "Daloopa",
        "platform_zh": "Daloopa",
        "product_or_resource": "Daloopa financial models and KPI data",
        "domain_en": "Financial fundamentals and modeling data",
        "domain_zh": "金融基本面与建模数据",
        "country_region": "Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap API/exported model data under enterprise terms",
        "official_sdk_api": "Request demo, enterprise account, and API key access",
        "source_url": "https://daloopa.com/",
        "official_status_en": "Official source",
        "official_status_zh": "官方来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Contract pricing; commercial use and embedded model use require agreement",
        "risk_level": "High",
        "description_en": "Structured financial models, company KPI data, spreadsheet-ready fundamentals, and API/export workflows for modeling and KPI extraction agents.",
        "description_zh": "面向建模和 KPI 提取 Agent 的结构化财务模型、公司 KPI、表格化基本面数据和 API/导出工作流。",
        "sort_order": 230,
    },
    {
        "resource_id": "aar-0231",
        "platform_en": "PitchBook",
        "platform_zh": "PitchBook",
        "product_or_resource": "PitchBook Direct Data and private markets data",
        "domain_en": "Private markets and alternative data",
        "domain_zh": "一级市场与另类数据",
        "country_region": "Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap Direct Data/API under enterprise terms",
        "official_sdk_api": "Direct Data, API, and enterprise account access",
        "source_url": "https://pitchbook.com/",
        "official_status_en": "Official source",
        "official_status_zh": "官方来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Contract pricing; export, CRM sync, redistribution, and display rights required",
        "risk_level": "High",
        "description_en": "Private company, VC/PE, M&A, fund, investor, valuation, financing, deal, and Direct Data source for private-market diligence agents.",
        "description_zh": "面向一级市场尽调 Agent 的私募公司、VC/PE、并购、基金、投资者、估值、融资、交易和 Direct Data 数据源。",
        "sort_order": 231,
    },
    {
        "resource_id": "aar-0232",
        "platform_en": "Chronograph",
        "platform_zh": "Chronograph",
        "product_or_resource": "Chronograph private capital GraphQL/API",
        "domain_en": "Private markets and alternative data",
        "domain_zh": "一级市场与另类数据",
        "country_region": "Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; wrap GraphQL/API only under approved-developer permissions",
        "official_sdk_api": "Request demo, approved developers, GraphQL, and API access",
        "source_url": "https://www.chronograph.pe/",
        "official_status_en": "Official source",
        "official_status_zh": "官方来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Contract pricing; LP/GP private data permissions, audit, and access control required",
        "risk_level": "High",
        "description_en": "Private capital GP/LP data, portfolio monitoring, capital accounts, reporting, GraphQL, and API source for LP reporting and fund-operations agents.",
        "description_zh": "面向 LP 报告和基金运营 Agent 的私募资本 GP/LP 数据、组合监控、资本账户、报告、GraphQL 和 API 数据源。",
        "sort_order": 232,
    },
    {
        "resource_id": "aar-0233",
        "platform_en": "Egnyte",
        "platform_zh": "Egnyte",
        "product_or_resource": "Egnyte developer API for financial document/RAG workflows",
        "domain_en": "Enterprise document and data rooms",
        "domain_zh": "企业文档与数据室",
        "country_region": "Global",
        "resource_formats": "SDK/API;Plugin",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Suitable for document/RAG MCP with enterprise IAM, DLP, and audit controls",
        "official_sdk_api": "Developer Portal app, OAuth, API, and Secure & Govern API",
        "source_url": "https://developers.egnyte.com/",
        "official_status_en": "Official developer source",
        "official_status_zh": "官方开发者来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Enterprise SaaS subscription; internal permissions, audit, DLP, retention, and AI-use governance required",
        "risk_level": "High",
        "description_en": "Financial-services supporting source for internal research reports, contracts, diligence files, data rooms, permissions, OAuth redirect, and document RAG workflows.",
        "description_zh": "金融服务辅助来源，用于内部研究报告、合同、尽调资料、数据室、权限、OAuth redirect 和文档 RAG 工作流。",
        "sort_order": 233,
    },
    {
        "resource_id": "aar-0234",
        "platform_en": "Box",
        "platform_zh": "Box",
        "product_or_resource": "Box developer API for financial document/RAG workflows",
        "domain_en": "Enterprise document and data rooms",
        "domain_zh": "企业文档与数据室",
        "country_region": "Global",
        "resource_formats": "SDK/API;Plugin;MCP",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Official/community MCP ecosystem exists; production requires enterprise permission governance",
        "official_sdk_api": "Developer Console app, OAuth/JWT, API, and Developer Tokens",
        "source_url": "https://developer.box.com/",
        "official_status_en": "Official developer source",
        "official_status_zh": "官方开发者来源",
        "verification_status": "Confirmed from PDF/workbook assessment",
        "openness_level": "Enterprise SaaS subscription; internal permissions, audit, DLP, retention, and AI-use governance required",
        "risk_level": "High",
        "description_en": "Financial-services supporting source for internal knowledge bases, investment research documents, client materials, data rooms, full-text search, API, OAuth/JWT, and document RAG workflows.",
        "description_zh": "金融服务辅助来源，用于内部知识库、投研文档、客户材料、数据室、全文检索、API、OAuth/JWT 和文档 RAG 工作流。",
        "sort_order": 234,
    },
    {
        "resource_id": "aar-0235",
        "platform_en": "Financial Modeling Prep",
        "platform_zh": "Financial Modeling Prep / FMP",
        "product_or_resource": "FMP financial data API",
        "domain_en": "Financial data APIs",
        "domain_zh": "金融数据 API",
        "country_region": "US/Global",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; suitable for custom MCP in development/supplemental use",
        "official_sdk_api": "API key and REST APIs",
        "source_url": "https://site.financialmodelingprep.com/developer/docs/pricing",
        "official_status_en": "Official developer source",
        "official_status_zh": "官方开发者来源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Free tier plus paid plans; commercial display or redistribution requires data display/licensing agreement",
        "risk_level": "Medium",
        "description_en": "Lightweight overseas market/fundamental data API for stocks, ETFs, 13F, forex, crypto, commodities, ESG, financials, valuation, and news. Not recommended as high-reliability real-time production source.",
        "description_zh": "海外股票、ETF、13F、外汇、加密、商品、ESG、财报、估值和新闻的轻量金融数据 API；不建议作为高可靠实盘主源。",
        "sort_order": 235,
    },
    {
        "resource_id": "aar-0236",
        "platform_en": "SEC EDGAR",
        "platform_zh": "SEC EDGAR",
        "product_or_resource": "SEC EDGAR APIs and filing data",
        "domain_en": "Public financial filings and macro data",
        "domain_zh": "公共财报公告与宏观数据",
        "country_region": "US",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; suitable for filing search, XBRL parsing, and announcement summarization tools",
        "official_sdk_api": "REST API, JSON, XBRL, and filing metadata access",
        "source_url": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "official_status_en": "Official public source",
        "official_status_zh": "官方公共来源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Free public source; fair-access rules apply",
        "risk_level": "Medium",
        "description_en": "Official US filing source for 10-K, 10-Q, 8-K, 20-F, XBRL, filing metadata, financial statement parsing, RAG, and event detection.",
        "description_zh": "美国 10-K、10-Q、8-K、20-F、XBRL、filings metadata、财报解析、RAG 和事件检测的官方公告来源。",
        "sort_order": 236,
    },
    {
        "resource_id": "aar-0237",
        "platform_en": "FRED",
        "platform_zh": "FRED",
        "product_or_resource": "FRED API macroeconomic data",
        "domain_en": "Public financial filings and macro data",
        "domain_zh": "公共财报公告与宏观数据",
        "country_region": "US/Global macro",
        "resource_formats": "SDK/API;Data export",
        "source_format": "official_web",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "No official MCP; suitable for macro time-series tools",
        "official_sdk_api": "API key and REST API",
        "source_url": "https://fred.stlouisfed.org/docs/api/fred/",
        "official_status_en": "Official public source",
        "official_status_zh": "官方公共来源",
        "verification_status": "Confirmed from assessment workbook",
        "openness_level": "Free API; follow API terms and attribution rules",
        "risk_level": "Low",
        "description_en": "Official macroeconomic time-series source for rates, inflation, employment, GDP, financial conditions, historical vintages, and economic indicators.",
        "description_zh": "利率、通胀、就业、GDP、金融条件、历史 vintage 和经济指标的官方宏观时间序列来源。",
        "sort_order": 237,
    },
]


ENTITY_OVERRIDES = {
    "ent-sse-info-szse-information": {
        "official_homepage": "https://www.sseinfo.com/services/assortment/level1/",
        "primary_github": "",
        "primary_docs": "https://www.sseinfo.com/aboutus/authstatement/",
        "commercial_model": "Exchange/data-company license; display, non-display, redistribution, and derived-data rights must be confirmed separately",
    },
    "ent-china-futures-ctp-exchange-authorized-futures-market-data": {
        "official_homepage": "https://www.shfe.com.cn/",
        "primary_github": "",
        "primary_docs": "https://www.shfe.com.cn/",
        "commercial_model": "Broker, CTP, leased-line, account, trading, and exchange data permissions required",
    },
    "ent-hkex-real-time-data-services": {
        "official_homepage": "https://www.hkex.com.hk/Services/Market-Data-Services/Real-Time-Data-Services/Overview?sc_lang=en",
        "primary_github": "",
        "primary_docs": "https://www.hkex.com.hk/Services/Market-Data-Services/Real-Time-Data-Services/Overview?sc_lang=en",
        "commercial_model": "HKEX licensed data or authorized vendor contract; display, non-display, and redistribution rights required",
    },
    "ent-wind": {
        "official_homepage": "https://www.wind.com.cn/",
        "primary_github": "https://github.com/Wind-Information-Co-Ltd/wind-skills",
        "primary_docs": "https://www.wind.com.cn/",
        "commercial_model": "Enterprise contract; API, display, non-display, external distribution, and derived-data rights must be confirmed",
    },
    "ent-ifind": {
        "official_homepage": "https://www.51ifind.com/",
        "primary_github": "",
        "primary_docs": "https://mcp.51ifind.com",
        "commercial_model": "Enterprise contract; API, display, redistribution, and external-client use require authorization",
    },
    "ent-eastmoney-choice": {
        "official_homepage": "https://choice.eastmoney.com/",
        "primary_github": "",
        "primary_docs": "https://choice.eastmoney.com/",
        "commercial_model": "Commercial contract; external display and redistribution require confirmation",
    },
    "ent-lseg": {
        "official_homepage": "https://www.lseg.com/",
        "primary_github": "https://github.com/LSEG-API-Samples/Example.DataLibrary.Python",
        "primary_docs": "https://www.lseg.com/en/data-analytics/financial-data",
        "commercial_model": "Enterprise contract; content, user, use-case, latency, and distribution scope are priced separately",
    },
    "ent-bloomberg": {
        "official_homepage": "https://www.bloomberg.com/professional/",
        "primary_github": "",
        "primary_docs": "https://www.bloomberg.com/professional/products/data/",
        "commercial_model": "Enterprise contract; exchange fees, terminal/server/API rights, and redistribution restrictions apply",
    },
    "ent-bloomberg-enterprise-b-pipe": {
        "official_homepage": "https://www.bloomberg.com/professional/products/data/",
        "primary_github": "",
        "primary_docs": "https://www.bloomberg.com/professional/products/data/",
        "commercial_model": "Enterprise contract; exchange fees, terminal/server/API rights, and redistribution restrictions apply",
    },
    "ent-cme-group-market-data": {
        "official_homepage": "https://www.cmegroup.com/market-data.html",
        "primary_github": "",
        "primary_docs": "https://www.cmegroup.com/market-data.html",
        "commercial_model": "Exchange data license; commercial, display, non-display, and redistribution rights required",
    },
    "ent-factset": {
        "official_homepage": "https://www.factset.com/",
        "primary_github": "https://github.com/factset",
        "primary_docs": "https://developer.factset.com/",
        "commercial_model": "Enterprise contract; API, display, non-display, and external distribution rights require confirmation",
    },
    "ent-s-p-global-market-intelligence": {
        "official_homepage": "https://www.spglobal.com/marketintelligence/",
        "primary_github": "",
        "primary_docs": "https://developer.spglobal.com/",
        "commercial_model": "Enterprise contract; credit-rating, display, distribution, and AI-use rights require confirmation",
    },
    "ent-morningstar": {
        "official_homepage": "https://www.morningstar.com/business",
        "primary_github": "",
        "primary_docs": "https://developer.morningstar.com/",
        "commercial_model": "Enterprise contract; fund ratings, client reporting, and advisory use require authorization",
    },
    "ent-moody-s": {
        "official_homepage": "https://developer.moodys.com/",
        "primary_github": "",
        "primary_docs": "https://developer.moodys.com/",
        "commercial_model": "Enterprise contract; ratings, credit research, AI use, and redistribution restrictions are strict",
    },
    "ent-mt-newswires": {
        "official_homepage": "https://www.mtnewswires.com/",
        "primary_github": "",
        "primary_docs": "https://www.mtnewswires.com/",
        "commercial_model": "Enterprise news-feed contract; copyright, AI summaries, caching, display, and redistribution require permission",
    },
    "ent-aiera": {
        "official_homepage": "https://www.aiera.com/",
        "primary_github": "",
        "primary_docs": "https://www.aiera.com/",
        "commercial_model": "Enterprise contract; transcript, summary, redistribution, and client-output rights required",
    },
    "ent-daloopa": {
        "official_homepage": "https://daloopa.com/",
        "primary_github": "",
        "primary_docs": "https://daloopa.com/",
        "commercial_model": "Enterprise contract; commercial use and embedded model use require authorization",
    },
    "ent-pitchbook": {
        "official_homepage": "https://pitchbook.com/",
        "primary_github": "",
        "primary_docs": "https://pitchbook.com/",
        "commercial_model": "Enterprise contract; export, CRM sync, redistribution, and display rights required",
    },
    "ent-chronograph": {
        "official_homepage": "https://www.chronograph.pe/",
        "primary_github": "",
        "primary_docs": "https://www.chronograph.pe/",
        "commercial_model": "Enterprise contract; LP/GP private data permissions, audit, and access control required",
    },
    "ent-egnyte": {
        "official_homepage": "https://developers.egnyte.com/",
        "primary_github": "",
        "primary_docs": "https://developers.egnyte.com/",
        "commercial_model": "Enterprise SaaS subscription; IAM, DLP, audit, retention, and AI-use governance required",
    },
    "ent-box": {
        "official_homepage": "https://developer.box.com/",
        "primary_github": "",
        "primary_docs": "https://developer.box.com/",
        "commercial_model": "Enterprise SaaS subscription; IAM, DLP, audit, retention, and AI-use governance required",
    },
    "ent-financial-modeling-prep": {
        "official_homepage": "https://site.financialmodelingprep.com/developer/docs/pricing",
        "primary_github": "",
        "primary_docs": "https://site.financialmodelingprep.com/developer/docs/pricing",
        "commercial_model": "Free tier plus paid plans; commercial display or redistribution requires data display/licensing agreement",
    },
    "ent-sec-edgar": {
        "official_homepage": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "primary_github": "",
        "primary_docs": "https://www.sec.gov/search-filings/edgar-application-programming-interfaces",
        "commercial_model": "Free public source; fair-access rules apply",
    },
    "ent-fred": {
        "official_homepage": "https://fred.stlouisfed.org/docs/api/fred/",
        "primary_github": "",
        "primary_docs": "https://fred.stlouisfed.org/docs/api/fred/",
        "commercial_model": "Free API; follow API terms and attribution rules",
    },
    "ent-interactive-brokers": {
        "official_homepage": "https://www.interactivebrokers.com/",
        "primary_github": "https://github.com/InteractiveBrokers/tws-api-public",
        "primary_docs": "https://ibkrcampus.com/campus/ibkr-api-page/cpapi-v1/",
        "commercial_model": "Brokerage account plus market-data subscriptions; trading and redistribution permissions must be controlled",
    },
    "ent-alpaca": {
        "official_homepage": "https://alpaca.markets/",
        "primary_github": "https://github.com/alpacahq/alpaca-py",
        "primary_docs": "https://docs.alpaca.markets/us/docs/market-data-faq",
        "commercial_model": "Free plus paid subscriptions and broker/partner contracts; IEX, SIP, and trading permissions differ",
    },
    "ent-polygon-io": {
        "official_homepage": "https://polygon.io/",
        "primary_github": "https://github.com/massive-com/client-python",
        "primary_docs": "https://polygon.io/docs/rest/stocks/overview",
        "commercial_model": "Free/personal tiers plus business contracts; commercial display, redistribution, and exchange real-time data require authorization",
    },
    "ent-tushare-pro": {
        "official_homepage": "https://tushare.pro/",
        "primary_github": "https://github.com/waditu/tushare",
        "primary_docs": "https://tushare.pro/document/1?doc_id=463",
        "commercial_model": "Points and paid memberships; commercial display, redistribution, and production use require contract review",
    },
    "ent-akshare": {
        "official_homepage": "https://akshare.akfamily.xyz/",
        "primary_github": "https://github.com/akfamily/akshare",
        "primary_docs": "https://akshare.akfamily.xyz/introduction.html",
        "commercial_model": "Free open-source research tool; commercial and production risk remains with the user",
    },
}


def entity_id(name: str) -> str:
    import re

    text = name.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return f"ent-{text[:60] or 'unknown'}"


def upsert_data_source(conn: sqlite3.Connection, row: dict[str, object]) -> None:
    values = {field: row.get(field, "") for field in FIELDS}
    values["source_dataset"] = SOURCE_BATCH
    values["checked_at"] = TODAY
    conn.execute("DELETE FROM data_sources WHERE resource_id = ?", (values["resource_id"],))
    conn.execute(
        f"""
        INSERT INTO data_sources ({", ".join(FIELDS)})
        VALUES ({", ".join("?" for _ in FIELDS)})
        """,
        [values[field] for field in FIELDS],
    )


def apply_entity_overrides(conn: sqlite3.Connection) -> None:
    for eid, row in ENTITY_OVERRIDES.items():
        conn.execute(
            """
            UPDATE tracked_entities
            SET official_homepage = ?,
                primary_github = ?,
                primary_docs = ?,
                commercial_model = ?,
                tracking_status = 'needs_review',
                checked_at = ?
            WHERE entity_id = ?
            """,
            (
                row["official_homepage"],
                row["primary_github"],
                row["primary_docs"],
                row["commercial_model"],
                TODAY,
                eid,
            ),
        )


def main() -> int:
    conn = sqlite3.connect(DB_PATH)
    try:
        for row in ROWS:
            upsert_data_source(conn, row)
        apply_entity_overrides(conn)
        conn.commit()
    finally:
        conn.close()
    print(f"upserted {len(ROWS)} financial FDE tracking rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
