#!/usr/bin/env python3
"""Add Claude Science and life-sciences plugin tracking sources."""

from __future__ import annotations

import sqlite3
from datetime import date

from index_store import DB_PATH


TODAY = date.today().isoformat()


DATA_SOURCES = [
    {
        "resource_id": "aar-0203",
        "platform_en": "Anthropic",
        "platform_zh": "Anthropic",
        "product_or_resource": "Claude Science",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "Plugin;MCP;Skill;SDK/API",
        "source_format": "official_web",
        "official_cli": "Claude Code plugin workflow",
        "official_skill": "Claude Science skills and workflows",
        "official_mcp": "Life sciences marketplace MCP servers",
        "official_sdk_api": "Anthropic API and Claude platform",
        "source_url": "https://www.anthropic.com/news/claude-science-ai-workbench",
        "official_status_en": "Official",
        "official_status_zh": "官方",
        "verification_status": "Confirmed",
        "openness_level": "Commercial platform",
        "risk_level": "High",
        "description_en": "Anthropic's Claude Science workbench links Claude to life-sciences tools, data sources, MCP servers, skills, and BioNeMo integrations.",
        "description_zh": "Anthropic 的 Claude Science 科学工作台连接生命科学工具、数据源、MCP Server、Skill 和 BioNeMo 集成。",
        "source_dataset": "claude-science-research",
        "sort_order": 203,
    },
    {
        "resource_id": "aar-0204",
        "platform_en": "Anthropic Life Sciences Marketplace",
        "platform_zh": "Anthropic 生命科学 Marketplace",
        "product_or_resource": "Claude Code Life Sciences Marketplace",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "Plugin;MCP;Skill",
        "source_format": "github_repo",
        "official_cli": "Claude Code plugin marketplace add/install",
        "official_skill": "Life sciences skills",
        "official_mcp": "Remote and local MCP servers",
        "official_sdk_api": "",
        "source_url": "https://github.com/anthropics/life-sciences",
        "official_status_en": "Official",
        "official_status_zh": "官方",
        "verification_status": "Confirmed",
        "openness_level": "Mixed: public, free-account, paid, and institutional access",
        "risk_level": "High",
        "description_en": "Official Anthropic marketplace for life-sciences MCP servers and skills, including PubMed, BioRender, Synapse, Wiley, Consensus, Cortellis, AdisInsight, 10x Genomics, ChEMBL, ClinicalTrials.gov, Open Targets, bioRxiv, Medidata, ToolUniverse, and workflow skills.",
        "description_zh": "Anthropic 官方生命科学 MCP Server 和 Skill marketplace，包含 PubMed、BioRender、Synapse、Wiley、Consensus、Cortellis、AdisInsight、10x Genomics、ChEMBL、ClinicalTrials.gov、Open Targets、bioRxiv、Medidata、ToolUniverse 及工作流 Skill。",
        "source_dataset": "claude-science-research",
        "sort_order": 204,
    },
    {
        "resource_id": "aar-0205",
        "platform_en": "NVIDIA BioNeMo",
        "platform_zh": "NVIDIA BioNeMo",
        "product_or_resource": "BioNeMo Agent Toolkit",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "Skill;Plugin;SDK/API",
        "source_format": "github_repo",
        "official_cli": "skills CLI install flow",
        "official_skill": "BioNeMo agent skills",
        "official_mcp": "Plugin marketplace packaging",
        "official_sdk_api": "NVIDIA NIM and BioNeMo model APIs",
        "source_url": "https://github.com/NVIDIA-BioNeMo/bionemo-agent-toolkit",
        "official_status_en": "Official",
        "official_status_zh": "官方",
        "verification_status": "Confirmed",
        "openness_level": "Mixed: open repo plus NVIDIA service/model access",
        "risk_level": "High",
        "description_en": "NVIDIA BioNeMo Agent Toolkit provides agent skills for protein folding, molecular docking, generative chemistry, genomics, protein design, biomarker discovery, Boltz-2, DiffDock, Evo 2, GenMol, OpenFold, ProteinMPNN, RFdiffusion, Parabricks, and related workflows.",
        "description_zh": "NVIDIA BioNeMo Agent Toolkit 提供蛋白折叠、分子对接、生成式化学、基因组学、蛋白设计、生物标志物发现，以及 Boltz-2、DiffDock、Evo 2、GenMol、OpenFold、ProteinMPNN、RFdiffusion、Parabricks 等 Agent Skill。",
        "source_dataset": "claude-science-research",
        "sort_order": 205,
    },
    {
        "resource_id": "aar-0206",
        "platform_en": "PubMed",
        "platform_zh": "PubMed",
        "product_or_resource": "PubMed MCP server for Claude Life Sciences",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "PubMed / NCBI Entrez access",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/pubmed",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Public; no authentication required for the marketplace plugin",
        "risk_level": "Medium",
        "description_en": "PubMed plugin in Anthropic's life-sciences marketplace for biomedical literature search and article access; README states no authentication is required.",
        "description_zh": "Anthropic 生命科学 marketplace 中的 PubMed 插件，用于生物医学文献检索和文章访问；README 说明无需认证。",
        "source_dataset": "claude-science-research",
        "sort_order": 206,
    },
    {
        "resource_id": "aar-0207",
        "platform_en": "BioRender",
        "platform_zh": "BioRender",
        "product_or_resource": "BioRender MCP server for Claude Life Sciences",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "Canada/US",
        "resource_formats": "MCP;Plugin",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/biorender",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Free account required",
        "risk_level": "Medium",
        "description_en": "BioRender MCP server in the Anthropic marketplace for creating and accessing scientific illustrations; README states a free BioRender account is required.",
        "description_zh": "Anthropic marketplace 中的 BioRender MCP Server，用于创建和访问科学插图；README 说明需要免费 BioRender 账户。",
        "source_dataset": "claude-science-research",
        "sort_order": 207,
    },
    {
        "resource_id": "aar-0208",
        "platform_en": "Synapse",
        "platform_zh": "Synapse",
        "product_or_resource": "Synapse.org MCP server for Claude Life Sciences",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "Synapse platform API",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/synapse",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Free account required; dataset permissions vary",
        "risk_level": "High",
        "description_en": "Synapse.org MCP server by Sage Bionetworks for collaborative research data management; README states a free Synapse account is required.",
        "description_zh": "Sage Bionetworks 的 Synapse.org MCP Server，用于协作式科研数据管理；README 说明需要免费 Synapse 账户，数据权限因项目而异。",
        "source_dataset": "claude-science-research",
        "sort_order": 208,
    },
    {
        "resource_id": "aar-0209",
        "platform_en": "Wiley Scholar Gateway",
        "platform_zh": "Wiley Scholar Gateway",
        "product_or_resource": "Wiley Scholar Gateway MCP server",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "Global",
        "resource_formats": "MCP;SDK/API",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "Scholar Gateway access",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/wiley-scholar-gateway",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Free account required; publication access may depend on license",
        "risk_level": "Medium",
        "description_en": "Wiley Scholar Gateway MCP server in the Anthropic marketplace for academic research and publication access.",
        "description_zh": "Anthropic marketplace 中的 Wiley Scholar Gateway MCP Server，用于学术研究和出版物访问。",
        "source_dataset": "claude-science-research",
        "sort_order": 209,
    },
    {
        "resource_id": "aar-0210",
        "platform_en": "Consensus",
        "platform_zh": "Consensus",
        "product_or_resource": "Consensus MCP server",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "MCP;SDK/API",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "Consensus research search",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/consensus",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Account required",
        "risk_level": "Medium",
        "description_en": "Consensus MCP server for AI-powered search across peer-reviewed scientific research papers and evidence synthesis.",
        "description_zh": "Consensus MCP Server 用于跨同行评议科研论文的 AI 搜索和证据综合。",
        "source_dataset": "claude-science-research",
        "sort_order": 210,
    },
    {
        "resource_id": "aar-0211",
        "platform_en": "Cortellis",
        "platform_zh": "Cortellis",
        "product_or_resource": "Cortellis Regulatory Intelligence MCP server",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "Global",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "Cortellis regulatory intelligence access",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/cortellis",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Paid subscription or institutional access",
        "risk_level": "High",
        "description_en": "Clarivate Cortellis Regulatory Intelligence MCP server for global drug regulatory submissions, approvals, guidance, and intelligence; README states a Cortellis subscription is required.",
        "description_zh": "Clarivate Cortellis Regulatory Intelligence MCP Server，用于全球药品监管提交、批准、指南和情报；README 说明需要 Cortellis 订阅。",
        "source_dataset": "claude-science-research",
        "sort_order": 211,
    },
    {
        "resource_id": "aar-0212",
        "platform_en": "AdisInsight",
        "platform_zh": "AdisInsight",
        "product_or_resource": "AdisInsight MCP server",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "Global",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "AdisInsight drug development intelligence",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/adisinsight",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Paid subscription",
        "risk_level": "High",
        "description_en": "Springer Nature AdisInsight MCP server for drug development pipeline, clinical trials, safety, and deals intelligence; README states an AdisInsight subscription is required.",
        "description_zh": "Springer Nature AdisInsight MCP Server，用于药物研发管线、临床试验、安全性和交易情报；README 说明需要 AdisInsight 订阅。",
        "source_dataset": "claude-science-research",
        "sort_order": 212,
    },
    {
        "resource_id": "aar-0213",
        "platform_en": "10x Genomics",
        "platform_zh": "10x Genomics",
        "product_or_resource": "10x Genomics Cloud MCP server",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "10x Genomics Cloud analysis workflows",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/10x-genomics",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Account and access token required; useful only with user's own analysis data",
        "risk_level": "High",
        "description_en": "10x Genomics Cloud MCP server for accessing analysis data and workflows; README states an account, access token, and existing analysis data are required.",
        "description_zh": "10x Genomics Cloud MCP Server 用于访问分析数据和工作流；README 说明需要账户、访问令牌和已有分析数据。",
        "source_dataset": "claude-science-research",
        "sort_order": 213,
    },
    {
        "resource_id": "aar-0214",
        "platform_en": "ChEMBL",
        "platform_zh": "ChEMBL",
        "product_or_resource": "ChEMBL MCP server for Claude Life Sciences",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "UK/EU",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "ChEMBL database access",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/chembl",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Public",
        "risk_level": "Medium",
        "description_en": "ChEMBL plugin in Anthropic's life-sciences marketplace for bioactivity and drug discovery database access.",
        "description_zh": "Anthropic 生命科学 marketplace 中的 ChEMBL 插件，用于生物活性和药物发现数据库访问。",
        "source_dataset": "claude-science-research",
        "sort_order": 214,
    },
    {
        "resource_id": "aar-0215",
        "platform_en": "ClinicalTrials.gov",
        "platform_zh": "ClinicalTrials.gov",
        "product_or_resource": "ClinicalTrials.gov MCP server for Claude Life Sciences",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "ClinicalTrials.gov API",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/clinical-trials",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Public",
        "risk_level": "Medium",
        "description_en": "ClinicalTrials.gov plugin in Anthropic's life-sciences marketplace for public clinical trial registry data.",
        "description_zh": "Anthropic 生命科学 marketplace 中的 ClinicalTrials.gov 插件，用于公共临床试验注册数据。",
        "source_dataset": "claude-science-research",
        "sort_order": 215,
    },
    {
        "resource_id": "aar-0216",
        "platform_en": "Open Targets",
        "platform_zh": "Open Targets",
        "product_or_resource": "Open Targets MCP server for Claude Life Sciences",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "UK/EU",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "Open Targets Platform API",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/open-targets",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Public",
        "risk_level": "Medium",
        "description_en": "Open Targets plugin in Anthropic's life-sciences marketplace for drug target discovery and prioritization.",
        "description_zh": "Anthropic 生命科学 marketplace 中的 Open Targets 插件，用于药物靶点发现和优先级排序。",
        "source_dataset": "claude-science-research",
        "sort_order": 216,
    },
    {
        "resource_id": "aar-0217",
        "platform_en": "bioRxiv / medRxiv",
        "platform_zh": "bioRxiv / medRxiv",
        "product_or_resource": "bioRxiv and medRxiv MCP server for Claude Life Sciences",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "Global",
        "resource_formats": "MCP;SDK/API;Data export",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "bioRxiv / medRxiv preprint APIs",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/biorxiv",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Public",
        "risk_level": "Medium",
        "description_en": "bioRxiv and medRxiv plugin in Anthropic's life-sciences marketplace for preprint data access.",
        "description_zh": "Anthropic 生命科学 marketplace 中的 bioRxiv/medRxiv 插件，用于预印本数据访问。",
        "source_dataset": "claude-science-research",
        "sort_order": 217,
    },
    {
        "resource_id": "aar-0218",
        "platform_en": "ToolUniverse",
        "platform_zh": "ToolUniverse",
        "product_or_resource": "ToolUniverse MCP server",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "Global",
        "resource_formats": "MCP;SDK/API;Skill",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "Anthropic life-sciences marketplace plugin",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/tooluniverse",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Needs review",
        "risk_level": "High",
        "description_en": "ToolUniverse plugin in Anthropic's life-sciences marketplace for AI agents and tools for scientific discovery and automation.",
        "description_zh": "Anthropic 生命科学 marketplace 中的 ToolUniverse 插件，用于科学发现和自动化的 AI Agent 工具。",
        "source_dataset": "claude-science-research",
        "sort_order": 218,
    },
    {
        "resource_id": "aar-0219",
        "platform_en": "Medidata",
        "platform_zh": "Medidata",
        "product_or_resource": "Medidata MCP Connector for Claude",
        "domain_en": "Life sciences and biomedical research",
        "domain_zh": "生命科学与生物医学研究",
        "country_region": "US/Global",
        "resource_formats": "MCP;SDK/API",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "",
        "official_mcp": "Anthropic life-sciences marketplace plugin",
        "official_sdk_api": "Medidata platform access",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/medidata",
        "official_status_en": "Official marketplace plugin",
        "official_status_zh": "官方 marketplace 插件",
        "verification_status": "Confirmed",
        "openness_level": "Commercial platform access",
        "risk_level": "High",
        "description_en": "Medidata MCP Connector for Claude with platform help and predictive site ranking for clinical trials.",
        "description_zh": "Medidata MCP Connector for Claude，提供平台帮助和临床试验预测性中心排序能力。",
        "source_dataset": "claude-science-research",
        "sort_order": 219,
    },
    {
        "resource_id": "aar-0220",
        "platform_en": "scvi-tools",
        "platform_zh": "scvi-tools",
        "product_or_resource": "scvi-tools Claude Life Sciences skill",
        "domain_en": "Bioinformatics and scientific software",
        "domain_zh": "生物信息与科学软件",
        "country_region": "Global",
        "resource_formats": "Skill;SDK/API",
        "source_format": "github_repo",
        "official_cli": "",
        "official_skill": "Anthropic life-sciences marketplace skill",
        "official_mcp": "",
        "official_sdk_api": "scvi-tools Python toolkit",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/scvi-tools",
        "official_status_en": "Official marketplace skill",
        "official_status_zh": "官方 marketplace Skill",
        "verification_status": "Confirmed",
        "openness_level": "Open-source workflow skill",
        "risk_level": "Medium",
        "description_en": "Claude Life Sciences skill for single-cell omics analysis using scvi-tools, including model selection and integration workflows.",
        "description_zh": "Claude Life Sciences 的 scvi-tools Skill，用于单细胞组学分析、模型选择和整合工作流。",
        "source_dataset": "claude-science-research",
        "sort_order": 220,
    },
    {
        "resource_id": "aar-0221",
        "platform_en": "Nextflow / nf-core",
        "platform_zh": "Nextflow / nf-core",
        "product_or_resource": "Nextflow development Claude Life Sciences skill",
        "domain_en": "Bioinformatics and scientific software",
        "domain_zh": "生物信息与科学软件",
        "country_region": "Global",
        "resource_formats": "Skill;CLI;Data export",
        "source_format": "github_repo",
        "official_cli": "Nextflow and Docker workflow",
        "official_skill": "Anthropic life-sciences marketplace skill",
        "official_mcp": "",
        "official_sdk_api": "GEO/SRA public sequencing data workflow support",
        "source_url": "https://github.com/anthropics/life-sciences/tree/main/nextflow-development",
        "official_status_en": "Official marketplace skill",
        "official_status_zh": "官方 marketplace Skill",
        "verification_status": "Confirmed",
        "openness_level": "Open-source workflow; can use public GEO/SRA data",
        "risk_level": "High",
        "description_en": "Claude Life Sciences skill for running nf-core Nextflow pipelines such as rnaseq, sarek, and atacseq on local or public GEO/SRA sequencing data.",
        "description_zh": "Claude Life Sciences 的 Nextflow Skill，用于在本地或公共 GEO/SRA 测序数据上运行 rnaseq、sarek、atacseq 等 nf-core 流程。",
        "source_dataset": "claude-science-research",
        "sort_order": 221,
    },
]


TRACKED_ENTITY_OVERRIDES = {
    "ent-anthropic": {
        "official_homepage": "https://www.anthropic.com/",
        "primary_github": "https://github.com/anthropics/life-sciences",
        "primary_docs": "https://www.anthropic.com/news/claude-science-ai-workbench",
        "commercial_model": "Commercial platform; marketplace includes public, free-account, paid, and institutional resources",
        "service_description_en": "Anthropic provides Claude Science, Claude Code plugins, life-sciences MCP servers, skills, and API/platform access for scientific workflows.",
        "service_description_zh": "Anthropic 提供 Claude Science、Claude Code 插件、生命科学 MCP Server、Skill 以及科学工作流相关 API/平台访问。",
    }
}


ENTITY_LINKS = {
    "ent-anthropic-life-sciences-marketplace": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences"),
    "ent-nvidia-bionemo": ("https://github.com/NVIDIA-BioNeMo/bionemo-agent-toolkit", "https://github.com/NVIDIA-BioNeMo/bionemo-agent-toolkit"),
    "ent-pubmed": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/pubmed"),
    "ent-biorender": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/biorender"),
    "ent-synapse": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/synapse"),
    "ent-wiley-scholar-gateway": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/wiley-scholar-gateway"),
    "ent-consensus": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/consensus"),
    "ent-cortellis": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/cortellis"),
    "ent-adisinsight": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/adisinsight"),
    "ent-10x-genomics": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/10x-genomics"),
    "ent-chembl": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/chembl"),
    "ent-clinicaltrials": ("", "https://github.com/anthropics/life-sciences/tree/main/clinical-trials"),
    "ent-open-targets": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/open-targets"),
    "ent-biorxiv-medrxiv": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/biorxiv"),
    "ent-tooluniverse": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/tooluniverse"),
    "ent-medidata": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/medidata"),
    "ent-scvi-tools": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/scvi-tools"),
    "ent-nextflow-nf-core": ("https://github.com/anthropics/life-sciences", "https://github.com/anthropics/life-sciences/tree/main/nextflow-development"),
}


FIELDS = [
    "resource_id",
    "platform_en",
    "platform_zh",
    "product_or_resource",
    "domain_en",
    "domain_zh",
    "country_region",
    "resource_formats",
    "source_format",
    "official_cli",
    "official_skill",
    "official_mcp",
    "official_sdk_api",
    "source_url",
    "official_status_en",
    "official_status_zh",
    "verification_status",
    "openness_level",
    "risk_level",
    "description_en",
    "description_zh",
    "source_dataset",
    "checked_at",
    "sort_order",
]


def upsert_data_source(conn: sqlite3.Connection, row: dict[str, object]) -> None:
    values = {field: row.get(field, "") for field in FIELDS}
    values["checked_at"] = TODAY
    placeholders = ", ".join("?" for _ in FIELDS)
    conn.execute("DELETE FROM data_sources WHERE resource_id = ?", (values["resource_id"],))
    conn.execute(
        f"""
        INSERT INTO data_sources ({", ".join(FIELDS)})
        VALUES ({placeholders})
        """,
        [values[field] for field in FIELDS],
    )


def apply_entity_overrides(conn: sqlite3.Connection) -> None:
    for entity_id, row in TRACKED_ENTITY_OVERRIDES.items():
        conn.execute(
            """
            UPDATE tracked_entities
            SET official_homepage = ?,
                primary_github = ?,
                primary_docs = ?,
                commercial_model = ?,
                service_description_en = ?,
                service_description_zh = ?,
                tracking_status = 'needs_review',
                checked_at = ?
            WHERE entity_id = ?
            """,
            (
                row["official_homepage"],
                row["primary_github"],
                row["primary_docs"],
                row["commercial_model"],
                row["service_description_en"],
                row["service_description_zh"],
                TODAY,
                entity_id,
            ),
        )
    for entity_id, (github, docs) in ENTITY_LINKS.items():
        conn.execute(
            """
            UPDATE tracked_entities
            SET primary_github = COALESCE(NULLIF(?, ''), primary_github),
                primary_docs = ?,
                tracking_status = CASE
                    WHEN tracking_status = 'needs_source' THEN 'needs_review'
                    ELSE tracking_status
                END,
                checked_at = ?
            WHERE entity_id = ?
            """,
            (github, docs, TODAY, entity_id),
        )


def main() -> int:
    conn = sqlite3.connect(DB_PATH)
    try:
        for row in DATA_SOURCES:
            upsert_data_source(conn, row)
        apply_entity_overrides(conn)
        conn.commit()
    finally:
        conn.close()
    print(f"upserted {len(DATA_SOURCES)} Claude Science tracking rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
